public class GetProjectList{
	public class Data {
		public Integer totalProjectCount;
		public Object filterInd;
		public List<ProjectList> projectList;
	}

	public Data data;

	public class PortfolioProjectList_Z {
		public Object lockedBy;
		public Object projectAssumptions;
		public Object organizationProjects;
		public Object organization;
		public Boolean portfolio;
		public Boolean changesPending;
		public Integer solicitedOrgId;
		public String notes;
		public Integer parentId;
		public Object portfolioProjectList;
		public Object solicitedProjectId;
		public Double percentCompletion;
		public Object projectDetailLogs;
		public Boolean isLocked;
		public Object solicitedUsers;
		public Object portfolioProjectId;
		public Object partialSolicitationInd;
		public Object consolidateInd;
		public String projectDescription;
		public String shortName;
		public Object cs;
		public Object financeRmId;
		public Object goal;
		public Object listedAt;
		public Integer published;
		public Object numberRejections;
		public Object primaryUser;
		public Integer review;
		public Object salesRmId;
		public String scsEvaluation;
		public Object scsScore;
		public Object projectUsers;
		public Boolean parentInd;
		public Boolean coBrandInd;
		public Object orgIdList;
		public Long createdAt;
		public String createdBy;
		public Long updatedAt;
		public String updatedBy;
		public Integer orgId;
		public Integer projectId;
		public Boolean isActive;
		public Object value;
		public String status;
		public Object stage;
	}

	public class ProjectList {
		public Object lockedBy;
		public Object projectAssumptions;
		public Object organizationProjects;
		public Object organization;
		public Boolean portfolio;
		public Boolean changesPending;
		public Object solicitedOrgId;
		public Object notes;
		public Object parentId;
		public Object portfolioProjectList;
		public Object solicitedProjectId;
		public Double percentCompletion;
		public Object projectDetailLogs;
		public Object isLocked;
		public Object solicitedUsers;
		public Object portfolioProjectId;
		public Object partialSolicitationInd;
		public Object consolidateInd;
		public String projectDescription;
		public String shortName;
		public Object cs;
		public Object financeRmId;
		public Object goal;
		public Object listedAt;
		public Integer published;
		public Object numberRejections;
		public Object primaryUser;
		public Integer review;
		public Object salesRmId;
		public Object scsEvaluation;
		public Object scsScore;
		public Object projectUsers;
		public Boolean parentInd;
		public Boolean coBrandInd;
		public Object orgIdList;
		public Long createdAt;
		public String createdBy;
		public Long updatedAt;
		public String updatedBy;
		public Integer orgId;
		public Integer projectId;
		public Boolean isActive;
		public Object value;
		public String status;
		public Object stage;
	}
}